zap:
  level: debug
  file: /tmp/v2ex.log
  maxSize: 10
  maxAge: 7
http:
  listenAddr: ":12321"
  listenAddrTLS:
  certFile:
  keyFile:
  proxy:
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: v2ex
  maxOpenConnections: 100
  maxIdleConnections: 10
v2ex:
  token: