version: '3'
services:
  neutron:
    image: v2ex:nightly
    container_name: v2ex
    volumes:
      - "./config.yaml:/app/config.yaml"
      - "./static:/app/static"
      - "./v2ex.log:/tmp/v2ex.log"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: "host"